python3 behavioral_evals/generate_completions.py --ckpt /scr/akchak/rl_behaviors/checkpoints/all_strategies_ppo/global_step_20/ --dataset /scr/akchak/countdown/test.parquet --output-path /scr/akchak/rl_behaviors/outputs/all_strategies/ ; \
python3 behavioral_evals/generate_completions.py --ckpt /scr/akchak/rl_behaviors/checkpoints/all_strategies_ppo/global_step_30/ --dataset /scr/akchak/countdown/test.parquet --output-path /scr/akchak/rl_behaviors/outputs/all_strategies/ ; \
python3 behavioral_evals/generate_completions.py --ckpt /scr/akchak/rl_behaviors/checkpoints/all_strategies_ppo/global_step_40/ --dataset /scr/akchak/countdown/test.parquet --output-path /scr/akchak/rl_behaviors/outputs/all_strategies/ ; \
python3 behavioral_evals/generate_completions.py --ckpt /scr/akchak/rl_behaviors/checkpoints/all_strategies_ppo/global_step_50/ --dataset /scr/akchak/countdown/test.parquet --output-path /scr/akchak/rl_behaviors/outputs/all_strategies/ ; \
python3 behavioral_evals/generate_completions.py --ckpt /scr/akchak/rl_behaviors/checkpoints/all_strategies_ppo/global_step_60/ --dataset /scr/akchak/countdown/test.parquet --output-path /scr/akchak/rl_behaviors/outputs/all_strategies/ ; \
python3 behavioral_evals/generate_completions.py --ckpt /scr/akchak/rl_behaviors/checkpoints/all_strategies_ppo/global_step_70/ --dataset /scr/akchak/countdown/test.parquet --output-path /scr/akchak/rl_behaviors/outputs/all_strategies/ ; \
python3 behavioral_evals/generate_completions.py --ckpt /scr/akchak/rl_behaviors/checkpoints/all_strategies_ppo/global_step_80/ --dataset /scr/akchak/countdown/test.parquet --output-path /scr/akchak/rl_behaviors/outputs/all_strategies/ ; \
python3 behavioral_evals/generate_completions.py --ckpt /scr/akchak/rl_behaviors/checkpoints/all_strategies_ppo/global_step_90/ --dataset /scr/akchak/countdown/test.parquet --output-path /scr/akchak/rl_behaviors/outputs/all_strategies/ ; \
python3 behavioral_evals/generate_completions.py --ckpt /scr/akchak/rl_behaviors/checkpoints/all_strategies_ppo/global_step_200/ --dataset /scr/akchak/countdown/test.parquet --output-path /scr/akchak/rl_behaviors/outputs/all_strategies/ ; \
python3 behavioral_evals/generate_completions.py --ckpt /scr/akchak/rl_behaviors/checkpoints/all_strategies_ppo/global_step_210/ --dataset /scr/akchak/countdown/test.parquet --output-path /scr/akchak/rl_behaviors/outputs/all_strategies/ ; \
python3 behavioral_evals/generate_completions.py --ckpt /scr/akchak/rl_behaviors/checkpoints/all_strategies_ppo/global_step_220/ --dataset /scr/akchak/countdown/test.parquet --output-path /scr/akchak/rl_behaviors/outputs/all_strategies/ ; \
python3 behavioral_evals/generate_completions.py --ckpt /scr/akchak/rl_behaviors/checkpoints/all_strategies_ppo/global_step_230/ --dataset /scr/akchak/countdown/test.parquet --output-path /scr/akchak/rl_behaviors/outputs/all_strategies/ ; \
python3 behavioral_evals/generate_completions.py --ckpt /scr/akchak/rl_behaviors/checkpoints/all_strategies_ppo/global_step_240/ --dataset /scr/akchak/countdown/test.parquet --output-path /scr/akchak/rl_behaviors/outputs/all_strategies/ ; \
python3 behavioral_evals/generate_completions.py --ckpt /scr/akchak/rl_behaviors/checkpoints/all_strategies_ppo/global_step_250/ --dataset /scr/akchak/countdown/test.parquet --output-path /scr/akchak/rl_behaviors/outputs/all_strategies/
